// Generated by build.py from the Public tab of the Google Sheet. Do not edit by hand.
window.META = {"updated": "2026-09-23", "count": 49};
window.LISTS = {"mods": ["Ego mono", "Ego stereo / depth", "Teleop", "Manipulation / UMI", "Tactile", "Mocap / body", "Synthetic / sim", "Curation / all"], "region": ["North America", "China", "SE Asia & India", "Europe", "Korea"], "tier": ["Collector", "Curation & aggregation", "Simulation & synthetic", "Capture hardware"], "buyers": ["Figure", "Physical Intelligence", "Skild", "1X", "World Labs", "DeepMind", "NVIDIA", "Meta", "Amazon", "Tesla"]};
window.DATA = [
 {
  "name": "Mecka",
  "sub": "Human-motion capture at scale",
  "tier": "Collector",
  "mods": [
   "Ego mono",
   "Mocap / body"
  ],
  "region": [
   "North America",
   "China"
  ],
  "hq": "Toronto",
  "capture": "NYC, Shenzhen",
  "url": "https://www.mecka.ai/"
 },
 {
  "name": "Build AI",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America",
   "SE Asia & India"
  ],
  "hq": "San Francisco",
  "capture": "Southeast Asian factories",
  "sample": "Egocentric-100K",
  "url": "https://www.build.ai/",
  "sample_url": "https://huggingface.co/datasets/builddotai/Egocentric-100K"
 },
 {
  "name": "Human Archive",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America",
   "SE Asia & India"
  ],
  "hq": "San Francisco",
  "capture": "India",
  "sample": "Ego500",
  "url": "https://www.humanarchive.ai/",
  "sample_url": "https://ego500.humanarchive.ai/"
 },
 {
  "name": "Asimov",
  "sub": "YC W26",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America"
  ],
  "hq": "United States",
  "capture": "US contributors",
  "url": "https://tryasimov.ai/"
 },
 {
  "name": "Ropedia",
  "tier": "Collector",
  "mods": [
   "Ego stereo / depth",
   "Mocap / body"
  ],
  "region": [
   "SE Asia & India"
  ],
  "hq": "Singapore",
  "sample": "Xperience-10M",
  "url": "https://ropedia.com/",
  "sample_url": "https://ropedia.com/blog/20260316_xperience_10m"
 },
 {
  "name": "micro1",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco",
  "capture": "Gig workers in 50+ countries",
  "url": "https://www.micro1.ai/data-engine/capture-robotics-data"
 },
 {
  "name": "Humyn Labs",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America",
   "SE Asia & India"
  ],
  "hq": "San Francisco",
  "capture": "Bangalore",
  "url": "https://humynlabs.ai/"
 },
 {
  "name": "Provision",
  "sub": "fka Pronto",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America",
   "SE Asia & India"
  ],
  "hq": "San Francisco",
  "capture": "Bangalore"
 },
 {
  "name": "Pixelstwo",
  "tier": "Collector",
  "mods": [
   "Ego mono",
   "Tactile"
  ],
  "region": [
   "North America",
   "SE Asia & India"
  ],
  "hq": "United States",
  "capture": "India, Southeast Asia",
  "url": "https://pixelstwo.com/"
 },
 {
  "name": "Renlei Labs",
  "tier": "Collector",
  "mods": [
   "Ego mono",
   "Mocap / body"
  ],
  "capture": "Real workers on the job",
  "url": "https://renleilabs.com/"
 },
 {
  "name": "microagi",
  "sub": "fka Shift",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "Europe",
   "North America"
  ],
  "hq": "Munich, Zurich, London, NYC",
  "sample": "MicroAGI00 / MicroAGI01",
  "url": "https://www.microagi.ai/",
  "sample_url": "https://huggingface.co/MicroAGI-Labs"
 },
 {
  "name": "Miso",
  "sub": "Miso Motion",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "Korea",
   "North America"
  ],
  "hq": "Seoul, San Francisco",
  "url": "https://misomotion.com/"
 },
 {
  "name": "Midcentury",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco, NYC",
  "url": "https://www.midcentury.xyz/"
 },
 {
  "name": "Datoric",
  "sub": "YC S26",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco",
  "url": "https://www.datoric.com/"
 },
 {
  "name": "Index AI",
  "tier": "Collector",
  "mods": [
   "Ego mono",
   "Curation / all"
  ],
  "region": [
   "North America",
   "SE Asia & India"
  ],
  "hq": "San Francisco",
  "capture": "20+ suppliers across many countries",
  "url": "https://indexai.world/"
 },
 {
  "name": "Luel",
  "sub": "YC W26",
  "tier": "Curation & aggregation",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco",
  "sample": "Curated Ego4D / Ego-Exo4D subsets",
  "url": "https://www.luel.ai",
  "sample_url": "https://www.luel.ai/marketplace"
 },
 {
  "name": "XDOF",
  "tier": "Collector",
  "mods": [
   "Teleop",
   "Mocap / body"
  ],
  "region": [
   "North America",
   "SE Asia & India"
  ],
  "hq": "San Mateo",
  "capture": "Jakarta",
  "sample": "ABC-130K",
  "url": "https://www.xdof.ai",
  "sample_url": "https://huggingface.co/datasets/XDOF/ABC-130k"
 },
 {
  "name": "Config",
  "tier": "Collector",
  "mods": [
   "Manipulation / UMI"
  ],
  "url": "https://config.inc"
 },
 {
  "name": "Tacta Systems",
  "tier": "Collector",
  "mods": [
   "Tactile"
  ],
  "capture": "Real production lines",
  "sample": "Tacta Glove",
  "url": "https://www.tactasystems.com",
  "sample_url": "https://www.tactasystems.com"
 },
 {
  "name": "6thSense",
  "sub": "YC S26",
  "tier": "Collector",
  "mods": [
   "Tactile",
   "Ego mono"
  ],
  "url": "https://6thsense.dev"
 },
 {
  "name": "Reward AI",
  "tier": "Collector",
  "mods": [
   "Tactile"
  ],
  "sample": "Omnibody Hand",
  "url": "https://www.rewardai.com",
  "sample_url": "https://www.rewardai.com"
 },
 {
  "name": "AgiBot",
  "zh": "智元",
  "tier": "Collector",
  "mods": [
   "Teleop"
  ],
  "region": [
   "China"
  ],
  "hq": "Shanghai",
  "capture": "Own factory of 100+ teleoperated robots",
  "sample": "AgiBot World, 1M+ trajectories",
  "url": "https://www.agibot.com",
  "sample_url": "https://agibot-world.com/"
 },
 {
  "name": "Noitom Robotics",
  "tier": "Collector",
  "mods": [
   "Mocap / body",
   "Manipulation / UMI",
   "Ego mono"
  ],
  "region": [
   "China"
  ],
  "hq": "Beijing",
  "capture": "Shenzhen factory",
  "sample": "ModalityNet",
  "url": "https://noitomrobotics.com",
  "sample_url": "https://modalitynet.com/"
 },
 {
  "name": "Lightwheel",
  "zh": "光轮智能",
  "tier": "Collector",
  "mods": [
   "Ego mono",
   "Synthetic / sim"
  ],
  "region": [
   "China",
   "North America"
  ],
  "hq": "China / US",
  "capture": "20K+ hrs/week egocentric",
  "sample": "SimReady Library / EgoSuite",
  "url": "https://lightwheel.ai/",
  "sample_url": "https://lightwheel.ai/lightwheel-platform"
 },
 {
  "name": "Max Insights",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "China"
  ],
  "hq": "SF Bay Area",
  "url": "https://www.maxinsights.ai/"
 },
 {
  "name": "Genrobot",
  "tier": "Collector",
  "mods": [
   "Teleop"
  ],
  "region": [
   "China"
  ],
  "hq": "Beijing",
  "sample": "RealOmni-Open (10K hrs)",
  "url": "https://www.genrobot.ai/",
  "sample_url": "https://www.genrobot.ai/data/open-dataset"
 },
 {
  "name": "Shenbi",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "China"
  ],
  "hq": "China"
 },
 {
  "name": "Encord",
  "tier": "Curation & aggregation",
  "mods": [
   "Curation / all"
  ],
  "region": [
   "North America",
   "Europe"
  ],
  "hq": "San Francisco, London",
  "sample": "Physical AI data layer",
  "url": "https://encord.com/",
  "sample_url": "https://encord.com/physical-ai/"
 },
 {
  "name": "Orbifold AI",
  "tier": "Curation & aggregation",
  "mods": [
   "Ego stereo / depth",
   "Curation / all"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco",
  "url": "https://www.orbifold.ai/"
 },
 {
  "name": "Voxel51",
  "tier": "Curation & aggregation",
  "mods": [
   "Curation / all"
  ],
  "region": [
   "North America"
  ],
  "hq": "Ann Arbor",
  "sample": "FiftyOne",
  "url": "https://voxel51.com/",
  "sample_url": "https://voxel51.com/fiftyone"
 },
 {
  "name": "Scale AI",
  "tier": "Curation & aggregation",
  "mods": [
   "Curation / all",
   "Teleop",
   "Ego mono"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco",
  "sample": "Physical AI Data Engine",
  "url": "https://scale.com/",
  "sample_url": "https://scale.com/physical-ai"
 },
 {
  "name": "Turing",
  "tier": "Curation & aggregation",
  "mods": [
   "Curation / all"
  ],
  "region": [
   "North America"
  ],
  "hq": "Palo Alto",
  "sample": "Robotics data packs",
  "url": "https://www.turing.com/",
  "sample_url": "https://www.turing.com/advance/datasets/robotics"
 },
 {
  "name": "Protégé",
  "tier": "Curation & aggregation",
  "mods": [
   "Curation / all"
  ],
  "url": "https://www.withprotege.ai/"
 },
 {
  "name": "Sieve",
  "tier": "Curation & aggregation",
  "mods": [
   "Curation / all"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco",
  "url": "https://www.sieve.ai/"
 },
 {
  "name": "iMerit / Appen",
  "tier": "Curation & aggregation",
  "mods": [
   "Curation / all"
  ],
  "region": [
   "SE Asia & India"
  ],
  "hq": "India / Australia",
  "capture": "Managed collection campaigns",
  "url": "https://imerit.ai/"
 },
 {
  "name": "NVIDIA",
  "sub": "Cosmos · Isaac · GR00T",
  "tier": "Simulation & synthetic",
  "mods": [
   "Synthetic / sim"
  ],
  "region": [
   "North America"
  ],
  "hq": "Santa Clara",
  "sample": "GR00T N1",
  "url": "https://developer.nvidia.com/isaac/gr00t",
  "sample_url": "https://github.com/NVIDIA/Isaac-GR00T"
 },
 {
  "name": "Genesis AI",
  "tier": "Simulation & synthetic",
  "mods": [
   "Synthetic / sim"
  ],
  "url": "https://www.genesis.ai/"
 },
 {
  "name": "General Intuition",
  "sub": "Spun out of Medal",
  "tier": "Simulation & synthetic",
  "mods": [
   "Synthetic / sim"
  ],
  "sample": "2B+ game clips per year",
  "url": "https://www.generalintuition.com/"
 },
 {
  "name": "Moonlake AI",
  "tier": "Simulation & synthetic",
  "mods": [
   "Synthetic / sim"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco",
  "url": "https://moonlakeai.com/"
 },
 {
  "name": "SceniX",
  "tier": "Simulation & synthetic",
  "mods": [
   "Synthetic / sim"
  ],
  "url": "https://scenix.ai/"
 },
 {
  "name": "Antioch",
  "tier": "Simulation & synthetic",
  "mods": [
   "Synthetic / sim"
  ],
  "region": [
   "North America"
  ],
  "hq": "New York",
  "url": "https://antioch.com/"
 },
 {
  "name": "ReSim",
  "tier": "Simulation & synthetic",
  "mods": [
   "Synthetic / sim"
  ],
  "url": "https://www.resim.ai/"
 },
 {
  "name": "Orbbec",
  "tier": "Capture hardware",
  "mods": [
   "Ego stereo / depth"
  ],
  "region": [
   "China"
  ],
  "hq": "Shenzhen",
  "url": "https://www.orbbec.com/"
 },
 {
  "name": "Meta Project Aria",
  "tier": "Capture hardware",
  "mods": [
   "Ego stereo / depth"
  ],
  "region": [
   "North America"
  ],
  "hq": "Menlo Park",
  "sample": "Ego-Exo4D",
  "url": "https://www.projectaria.com/",
  "sample_url": "https://ego-exo4d-data.org/"
 },
 {
  "name": "HaptX",
  "tier": "Capture hardware",
  "mods": [
   "Tactile",
   "Teleop"
  ],
  "region": [
   "North America"
  ],
  "hq": "Seattle",
  "sample": "Gloves G1",
  "url": "https://haptx.com/",
  "sample_url": "https://haptx.com/gloves-g1/"
 },
 {
  "name": "Pico 4 Ultra + trackers",
  "tier": "Capture hardware",
  "mods": [
   "Ego stereo / depth",
   "Mocap / body"
  ],
  "url": "https://www.picoxr.com/global/products/pico4-ultra"
 },
 {
  "name": "Claru",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America"
  ],
  "hq": "San Francisco",
  "url": "https://claru.ai"
 },
 {
  "name": "WorldEngine",
  "sub": "Stealth, founded 2025",
  "tier": "Collector",
  "mods": [
   "Ego mono"
  ],
  "region": [
   "North America"
  ],
  "hq": "Santa Clara",
  "url": "https://worldengine.ai/"
 },
 {
  "name": "Defined.ai",
  "sub": "Formerly DefinedCrowd",
  "tier": "Curation & aggregation",
  "mods": [
   "Curation / all"
  ],
  "region": [
   "North America",
   "Europe"
  ],
  "hq": "Seattle, Lisbon",
  "sample": "Robotics datasets marketplace",
  "funding": "~$82M",
  "founders": "Daniela Braga",
  "url": "https://defined.ai/",
  "sample_url": "https://defined.ai/datasets?domain=robotics"
 }
];
